ProjectResponsiveWebSite
francisuloko/responsive-design-tnw pull request #1
Opened 2021-02-23 15:19 UTC by jaarkira

The project consists of cloning the webpage from the following link:

https://perma.cc/M5ZV-Q2D6

The project includes:
- Header
- Footer
- Highlight
- Latest funding

Every single part of the project was done so it's responsive to different size screen devices like cellphones, tablets, and big monitor desktops.

2021-02-24 00:39 UTC, rindrajosia requested changes
**INVALID** :cry:  :red_circle: 

Friendly reminder: You should make sure that your repo looks professional before review.
- [ ] Live demo link in your readme file doesn't work.
- [ ] There should be a screenshot in your readme file (Link is not enough, it should be displayed)

This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

Happy coding :muscle: 
Rindra Josia

2021-02-24 04:21 UTC, rindrajosia requested changes
Hello Team :wave:
Status: Changes Required :recycle:

Good job, your project is almost similar to the original.
But before approving this project let's cover a few details together to make it better :blush: :arrow_double_down: . I am sure that it will not take a lot of time:

REQUIRED:

- [ ] Remove all comments in your html and css files
- [ ] Don't use inline style in your html file (there are width and height properties in your `img` tag) 

### - [ ] Highlights section:
**1. All screen sizes:** 
* The title of each article should be embedded in a  **(a tag)**

**2. Desktop screen sizes:**
* There is a red overlay with a gradient in the top half of the first article.
* The date appears over the first article, at the top right corner

### - [ ] Latest Funding section
**1. All screen sizes:** 
* The title of the section should be embedded in a **(hx tag)**
* Each article title should be embedded in a **(hx tag)**

### - [ ] Footer: 
* Social media icons  should be embedded in a `nav` tag, 
* Below the social media menu, there is another menu also centered, and  should be embedded in a `nav` tag

That's it, you can submit another code review request after making these changes
With all my respect :pray:

Rindra Josia

2021-02-24 14:16 UTC, Chike1990 commented
You need to be more descriptive in your commits

2021-02-24 15:50 UTC, rindrajosia commented
> You need to be more descriptive in your commits

Hey, I have decided to rephrase my last review. I hope that it is more descriptive for you :+1:  :recycle:

2021-02-24 16:52 UTC, Chike1990 commented
> > You need to be more descriptive in your commits
> 
> Hey, I have decided to rephrase my last review. I hope that it is more descriptive for you 👍 ♻️

Great!! It looks good, bro

2021-02-25 00:09 UTC, mke2111 requested changes
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

### Hey @francisuloko & @jaarkira, 👋🏽 
**This is a great project you have going on, well-done lads and thanks for implementing the changes requested earlier on**. However, there are a few issues to fix to get approved.

### REQUIRED CHANGES: ⚠️ 

- [ ] Kindly add to the readme file the getting started procedures on a local computer. How to clone and run. This is part of what makes a readme professional.

- [ ] Kindly adjust the navbar spacing/padding in the header.
- Your clone
![Screenshot from 2021-02-25 03-18-14](https://user-images.githubusercontent.com/65501535/109084227-71607780-7718-11eb-8d2b-a945afb33572.png)

- Original site
![Screenshot from 2021-02-25 03-18-42](https://user-images.githubusercontent.com/65501535/109084257-7f15fd00-7718-11eb-92c9-a19d5a37b4dd.png)



- [x] Kindly make all the requested changes as requested by the previous reviewer. Read through the inline comments for clearer explanations.

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

## Reach me on slack for a chit-chat 🆘  Roy Mukuye

2021-02-25 00:11 UTC, mke2111 commented on index.html
> +            <a href="#">
**Kindly remove this anchor tag and enclose the title with it instead. 🔴**

2021-02-25 00:11 UTC, mke2111 commented on index.html
> +                        <h3>Opal cuts off your apps’ internet access to help you stop doomscrolling</h3>
Should be here instead. 🟢

2021-02-25 00:13 UTC, mke2111 commented on index.html
> +        <div class="main-feature divs">
This `div` tag should be an `article` tag instead. DO this for all highlights-articles 🔴

2021-02-25 00:14 UTC, mke2111 commented on index.html
> +        <div class="sub-feature flex">
`article` tag as well. 🔴

2021-02-25 00:33 UTC, mke2111 commented on index.html
> +            <a href="#">Calling young digital talent in the Netherlands – Be recognized in the T500 →</a>
This line of text should not be centered. Kindly refer to the original site.

2021-02-25 15:43 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi **TEAM**, congratulations on this project :fireworks: The README file has been fixed :muscle: The comments about the `<a>` tag and the title `<h*>` resolved :+1: The `<article>` tag have been included, overall our semantics are now better :fireworks: I hereby approve the project :smile: 

[Optional]
- Kindly consider reducing the font-size of the "Latest funding title" on mobile devices so it looks like the original
- Going forward, let us improve our project directory structure. We could create directories for assets where we have all our images in a directory, other files as well like the CSS file

Kindly go ahead and merge into development and do not forget to submit the project completion form :slightly_smiling_face: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-02-25 15:43 UTC, addod19 commented on styles.css
> +@media screen and (min-width: 822px) {
[Optional]
- We have a repeating media query!! Thus `line 313` and `line 626`. Kindly fix this

2021-02-25 15:43 UTC, addod19 commented on styles.css
> +@media screen and (min-width: 1024px) {
[Optional]
- We have a repeating media query!! Thus `line 489` and `line 705`. Kindly fix this

2021-02-25 16:25 UTC, francisuloko commented
Thank you @addod19 for reviewing and approving this project. Going forward we will apply your recommendations and fix the media queries.

2021-02-25 16:26 UTC, francisuloko commented
Thank you @rindrajosia and @mke2111 for your reviews and recommendations. Applying them was an awesome learning experience.

2021-02-25 16:26 UTC, merged